# docker-compose.yml
version: '3.8'

services:
  music-discovery-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: music-discovery-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Database Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      
      # External API Keys
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY:-}
      
      # System Configuration
      - ENVIRONMENT=production
      - DEBUG=false
      - ALLOWED_ORIGINS=["*"]
      - LOG_LEVEL=INFO
      
      # Playwright Configuration
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0
      
      # Optional Services
      - REDIS_URL=${REDIS_URL:-}
      - SENTRY_DSN=${SENTRY_DSN:-}
      
    volumes:
      # Persist Playwright browsers
      - playwright_browsers:/ms-playwright
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    networks:
      - music-discovery-network
      
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 1G
          cpus: "0.5"

volumes:
  playwright_browsers:
    driver: local

networks:
  music-discovery-network:
    driver: bridge
